// English translations
export const en = {
    // General
    appName: 'Kosmos Astro',
    appTitle: 'KOSMOS ASTRO',
    appDescription: 'Journey to the stars',
    hello: 'Hello',
    guest: 'Guest',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    cancel: 'Cancel',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    done: 'Done',
    search: 'Search',
    settings: 'Settings',
    profile: 'Profile',
    logout: 'Logout',
    login: 'Login',
    register: 'Register',
    skip: 'Skip',
    discover: 'Discover',
    continueButton: 'Continue',

    // Onboarding
    onboardingTitle1: 'Look at the Stars',
    onboardingSubtitle1: 'CONNECT WITH THE UNIVERSE',
    onboardingDesc1: 'Explore the world of astrology and connect with cosmic energies.',
    onboardingTitle2: 'Discover Your Future',
    onboardingSubtitle2: 'TAROT AND ASTROLOGY',
    onboardingDesc2: 'Unlock the secrets of your destiny with tarot cards and astrology.',
    onboardingTitle3: 'Begin Your Journey',
    onboardingSubtitle3: 'MEET YOUR GUIDES',
    onboardingDesc3: 'Let our expert astrologers guide your way.',

    // Auth
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    forgotPassword: 'Forgot Password',
    orContinueWith: 'or continue with',
    continueWithGoogle: 'Continue with Google',
    continueWithApple: 'Continue with Apple',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    signIn: 'Sign In',
    signUp: 'Sign Up',
    tagline: 'The journey to the stars',
    emailOrUsername: 'Email or Username',
    emailAddress: 'Email Address',
    username: 'Username',
    usernameTaken: 'This username is already taken',
    continueAsGuest: 'Continue as Guest',
    orText: 'or',
    termsNotice: 'By continuing, you agree to the Terms of Service',
    fillAllFields: 'Please fill in all fields',
    invalidEmail: 'Please enter a valid email address',
    enterUsername: 'Please enter a username',
    usernameTooShort: 'Username must be at least 3 characters',
    passwordsNoMatch: 'Passwords do not match',
    passwordTooShort: 'Password must be at least 6 characters',
    tooManyAttempts: 'Too many attempts. Please wait a few minutes before trying again.',
    connectionError: 'Could not connect to server. Please check your internet connection.',
    authFailed: 'An error occurred. Please try again.',
    verifyEmail: 'Verify Your Email',
    verifyEmailSubtitle: 'We sent a 6-digit code to',
    verifyCreateAccount: 'Verify & Create Account',
    enterSixDigitCode: 'Please enter the 6-digit code',
    resendCode: 'Resend Code',
    resendCodeIn: 'Resend code in',
    emailAlreadyRegistered: 'This email is already registered. Try signing in.',
    failedSendCode: 'Failed to send verification code.',
    registrationFailed: 'Registration failed. Please try again.',
    chooseLanguage: 'Choose Your Language',
    chooseLanguageSub: 'You can change this later in settings',
    changeLanguage: 'Change Language',
    changeLanguageSub: 'Select your preferred language',

    // Home
    advisors: 'Advisors',
    dailyMessage: 'Daily Message',
    seekingAnswer: 'Seeking Answer...',
    exploreAndCalculate: 'Explore & Calculate',
    premiumFeatures: 'Premium Features',
    pro: 'PRO',
    newFeature: 'New',

    // Features
    birthChart: 'Birth Chart',
    readYourFate: 'Read Your Fate',
    tarotReading: 'Tarot Reading',
    selectCards: 'Select Cards',
    palmReading: 'Palm Reading',
    readLines: 'Read Your Lines',
    coffeeReading: 'Coffee Fortune',
    traditionalFortune: 'Traditional Fortune',
    dreamInterpretation: 'Dream Interpretation',
    subconscious: 'Discover Subconscious',
    nameAnalysis: 'Name Analysis',
    numerology: 'Numerology',
    synastryCompatibility: 'Compatibility',
    loveAnalysis: 'Love Analysis',
    faceReading: 'Face Reading',
    physiognomy: 'Physiognomy',
    vedicChart: 'Vedic Chart',
    indianAstrology: 'Indian Astrology',
    angelCards: 'Angel Cards',
    messageFromAngels: 'Message from Angels',
    risingSign: 'Rising Sign',
    discoverYourMask: 'Discover Your Mask',
    planetHours: 'Planetary Hours',
    cosmicTiming: 'Cosmic Timing',
    findSoulmate: 'Find Soulmate',
    cosmicMatching: 'Cosmic Matching',
    drawSoulmate: 'Draw Soulmate',
    karmicPortrait: 'Karmic Portrait',

    // Moon Phases
    moonPhases: 'Moon Phases',
    moonPhaseNew: 'New Moon',
    moonPhaseNewDesc: 'Time for new beginnings',
    moonPhaseWaxingCrescent: 'Waxing Crescent',
    moonPhaseWaxingCrescentDesc: 'Set your intentions',
    moonPhaseFirstQuarter: 'First Quarter',
    moonPhaseFirstQuarterDesc: 'Take action',
    moonPhaseWaxingGibbous: 'Waxing Gibbous',
    moonPhaseWaxingGibbousDesc: 'Develop and improve',
    moonPhaseFull: 'Full Moon',
    moonPhaseFullDesc: 'Peak energy',
    moonPhaseWaningGibbous: 'Waning Gibbous',
    moonPhaseWaningGibbousDesc: 'Be grateful',
    moonPhaseLastQuarter: 'Last Quarter',
    moonPhaseLastQuarterDesc: 'Let go',
    moonPhaseWaningCrescent: 'Waning Crescent',
    moonPhaseWaningCrescentDesc: 'Rest and renew',

    // Streak
    dailyStreak: 'Daily Streak',
    claimReward: 'Claim Reward',
    streakDays: 'day streak',
    comeBackTomorrow: 'Come back tomorrow!',
    rewardClaimed: 'Reward claimed!',

    // Premium
    premium: 'Premium',
    goPremium: 'Go Premium',
    unlockAllFeatures: 'Unlock all features',
    monthlyPlan: 'Monthly Plan',
    yearlyPlan: 'Yearly Plan',
    bestValue: 'Best Value',
    freeTrial: 'Free Trial',

    // Tokens
    tokens: 'Gold',
    buyTokens: 'Buy Gold',
    watchAdForTokens: 'Watch Ad, Earn Gold',
    insufficientTokens: 'Insufficient gold',

    // Profile
    editProfile: 'Edit Profile',
    dayStreak: 'Day Streak',
    friends: 'Friends',
    earned: 'Earned',
    shareInviteCode: 'Share Invite Code',
    inviteFriends: 'Invite Friends',
    // Draw Soulmate
    revealSoulmate: 'Reveal Your Soulmate',
    soulmateSubtitle: 'Enter your birth details and let the stars paint a portrait of the one meant for you.',
    usingProfileData: 'Using your saved profile data',
    profileDataAvailable: 'Your profile data is available',
    useMyData: 'Use My Data',
    birthCity: 'Birth City',
    lookingFor: 'Looking For',
    genderFemale: 'Female',
    genderMale: 'Male',
    genderAny: 'Anyone',
    moonTokens: 'Moon Tokens',
    balance: 'Balance',
    generatePortrait: 'Generate Portrait',
    yourSoulmate: 'Your Soulmate',
    cosmicPortraitSubtitle: 'A cosmic portrait written in the stars',
    cosmicPortrait: 'COSMIC PORTRAIT',
    physicalTraits: 'Physical Traits',
    personalityLabel: 'Personality',
    whereYouMeet: 'Where You Might Meet',
    cosmicCompatibility: 'Cosmic Compatibility',
    sketching: 'Sketching…',
    soulmateProgress1: 'Reading the stars...',
    soulmateProgress2: 'Mapping celestial alignments...',
    soulmateProgress3: 'Sketching features...',
    soulmateProgress4: 'Adding cosmic details...',
    soulmateProgress5: 'Finalizing portrait...',
    // Dream Interpreter
    dreamInterpreter: 'Dream Interpreter',
    popularDreams: 'Popular dreams',
    interpreting: 'interpreting...',
    pastDreams: 'Past Dreams',
    noPastDreams: 'No past dreams recorded yet.',
    tellYourDream: 'Tell me your dream...',
    dreamSuggestion1: 'I was flying in my dream — what does it mean?',
    dreamSuggestion2: 'My teeth were falling out.',
    dreamSuggestion3: "I was being chased but couldn't run.",
    dreamSuggestion4: 'I saw someone who has passed away.',
    dreamSuggestion5: "I was late for an exam and couldn't find the room.",
    dreamSuggestion6: 'I was falling from a very high place.',
    // Tarot
    revealReading: 'Reveal Your Reading',
    tapCardsPre: 'Tap',
    tapCardsPost: 'more cards below',
    notEnoughTokensPremium: 'Not enough tokens. Visit Premium to get more.',
    yourSpread: 'Your Spread',
    upright: 'Upright',
    reversed: 'Reversed',
    combinedReading: 'Combined Reading',
    howCardsConnect: 'How your cards connect together',
    drawNewCards: 'Draw New Cards',
    posPast: 'Past',
    posPresent: 'Present',
    posFuture: 'Future',
    posPastDesc: 'What has passed',
    posPresentDesc: 'Current energy',
    posFutureDesc: 'What is to come',
    // Birth Chart
    birthChartUpper: 'BIRTH CHART',
    birthDateUpper: 'BIRTH DATE',
    birthTimeUpper: 'BIRTH TIME',
    birthCityUpper: 'BIRTH CITY',
    analysisResult: 'ANALYSIS RESULT',
    planetPositions: 'PLANET POSITIONS',
    elementBalance: 'ELEMENT BALANCE',
    qualityBalance: 'QUALITY BALANCE',
    yourSunSign: 'YOUR SUN SIGN',
    yourMoonSign: 'YOUR MOON SIGN',
    yourRisingSign: 'YOUR RISING SIGN',
    calculate: 'Calculate',
    newCalculation: 'New Calculation',
    confirm: 'Confirm',
    selectDate: 'SELECT DATE',
    selectTime: 'SELECT TIME',
    searchCity: 'Search city...',
    // Profile extras
    signOut: 'Sign Out',
    premiumActive: 'Premium Active',
    unlockPremium: 'Unlock Premium',
    allFeaturesUnlocked: 'All features unlocked',
    premiumPerks: 'Unlimited readings · AI insights · No ads',
    upgrade: 'Upgrade',
    becomeAstrologer: 'Become an Astrologer',
    becomeAstrologerSub: 'Share your wisdom and earn',
    referralReward: 'Earn 150 tokens for each friend you invite!',
    // Zodiac signs
    signAries: 'Aries', signTaurus: 'Taurus', signGemini: 'Gemini', signCancer: 'Cancer',
    signLeo: 'Leo', signVirgo: 'Virgo', signLibra: 'Libra', signScorpio: 'Scorpio',
    signSagittarius: 'Sagittarius', signCapricorn: 'Capricorn', signAquarius: 'Aquarius', signPisces: 'Pisces',
    elFire: 'Fire', elEarth: 'Earth', elAir: 'Air', elWater: 'Water',
    // Numerology
    fullName: 'Full Name',
    yourFullName: 'Your full name',
    useSavedBirthDate: 'Use saved birth date',
    nameNumber: 'Name Number',
    lifePathNumber: 'Life Path Number',
    cosmicConnection: 'Cosmic Connection',
    newAnalysis: 'New Analysis',
    dayLabel: 'Day',
    monthLabel: 'Month',
    yearLabel: 'Year',
    // Friends buttons
    addFriendBtn: 'Add',
    acceptBtn: 'Accept',
    rejectBtn: 'Reject',
    friendLabel: 'Friends',
    cancelRequest: 'Withdraw',
    wantsToBeFriends: 'wants to be friends',
    signOutConfirm: 'Are you sure you want to sign out?',
    comingSoon: 'Soon',
    comingSoonMsg: 'This feature is coming in an upcoming update.',
    pastConversations: 'Past Conversations',
    noPastConversations: 'No past conversations yet.',
    askAstroAI: 'Ask Astro AI...',
    thinkingShort: 'thinking...',
    love: 'Love',
    career: 'Career',
    health: 'Health',
    energy: 'Energy',
    luckyColor: 'Lucky Color',
    luckyNumber: 'Lucky Numbers',
    element: 'Element',
    dailyHoroscopeSuffix: 'Daily Horoscope',
    // Shared feature labels
    camera: 'Camera',
    gallery: 'Gallery',
    newReading: 'New Reading',
    retake: 'Retake',
    pleaseWait: 'Please wait...',
    // Synastry
    challenge: 'Challenge',
    dimensions: 'Dimensions',
    overall: 'OVERALL',
    selectSign: 'Select Sign',
    // Face Reading
    aiFaceAnalysis: 'AI Face Analysis',
    characterSummary: 'Character Summary',
    dominantElement: 'Dominant Element',
    facialRegionAnalysis: 'Facial Region Analysis',
    howItWorks: 'How it works',
    // Palm Reading
    alignPalmGuide: 'Align your palm with the guide',
    chooseAnalysis: 'Choose Analysis',
    deepInsights: 'Deep Insights',
    fingerShapeAnalysis: 'Finger Shape Analysis',
    moneyTriangle: 'Money Triangle',
    mountAnalysis: 'Mount Analysis',
    overallSummary: 'Overall Summary',
    palmLines: 'Palm Lines',
    palmistryAnalysis: 'Palmistry Analysis',
    relationshipLines: 'Relationship Lines',
    tipsGreatReading: 'Tips for a Great Reading',
    travelLines: 'Travel Lines',
    palmReadingReady: 'Your Palm Reading is Ready',
    // Coffee Fortune
    interpretingSymbols: 'Interpreting the symbols',
    readingGrounds: 'Reading the grounds...',
    yourReading: 'Your Reading',
    // Rising Sign
    birthYear: 'Birth Year',
    discoverRisingSign: 'Discover Your Rising Sign',
    faceYouShow: 'Discover the face you show to the world',
    selectBirthPlace: 'Select Birth Place',
    selectBirthTime: 'Select Birth Time',
    selectBirthYear: 'Select Birth Year',
    block: 'Block',
    unblock: 'Unblock',
    blocked: 'Blocked',
    requests: 'Requests',
    // Vedic Chart
    ancientWisdom: 'Ancient Wisdom of the East',
    ayurvedicConstitution: 'Ayurvedic Constitution',
    deity: 'Deity',
    kundliChart: 'Kundli Chart',
    meaning: 'Meaning',
    northIndian: 'North Indian',
    southIndian: 'South Indian',
    ruler: 'Ruler',
    rulingPlanet: 'Ruling Planet',
    lightOfSoul: 'Light of the Soul',
    mirrorOfMind: 'Mirror of the Mind',
    mythologicalDeity: 'Mythological Deity',
    outerPlanets: 'Outer Planets',
    // Find Soulmate / History / Astrologers
    yourSign: 'Your Sign',
    answer: 'Answer',
    consultants: 'Consultants',
    cosmicMessage: 'Cosmic Message',
    favorites: 'Favorites',
    historyTitle: 'History',
    question: 'Question',
    cosmicGuides: 'Cosmic Guides',
    mostPopular: 'Most Popular',
    additionalDetails: 'Additional Details',
    reportAstrologer: 'Report Astrologer',
    submitReport: 'Submit Report',
    reportReason: "What's the reason for this report?",
    addCaption: 'Add a caption...',
    messagePh: 'Message...',
    describeHappened: 'Optional: describe what happened...',
    response: 'Response',
    sessions: 'Sessions',
    specializations: 'Specializations',
    clientMessages: 'Client Messages',
    earnings: 'Earnings',
    client: 'Client',
    writeReply: 'Write your reply...',
    aboutYou: 'About You',
    applicationStatus: 'Application Status',
    personalInfo: 'Personal Information',
    prevNotApproved: 'Previous application not approved',
    selectExpertise: 'Select at least one area of expertise',
    specialties: 'Specialties',
    underReview: 'Under Review',
    canSubmitNew: 'You can submit a new application below.',
    experiencePh: 'Tell us about your experience and approach...',
    yearsExperiencePh: 'Years of experience',
    annualPlan: 'Annual Plan',
    billedYearly: 'Billed once per year',
    cancelAnytime: 'Cancel anytime',
    kosmosPremium: 'Kosmos Premium',
    moonTokensUpper: 'MOON TOKENS',
    privacyShort: 'Privacy',
    restore: 'Restore',
    subscription: 'SUBSCRIPTION',
    termsShort: 'Terms',
    tokenCostRef: 'Token Cost Reference',
    whatYouGet: 'WHAT YOU GET',
    promoCodePh: 'Promo code',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    emailCode: 'Email Code',
    emailVerified: 'Email verified',
    enterCurrentPassword: 'Enter your current password',
    passwordChanged: 'Password Changed',
    sendCode: 'Send Code',
    setNewPassword: 'Set your new password',
    verify: 'Verify',
    confirmNewPasswordPh: 'Confirm New Password',
    currentPasswordPh: 'Current Password',
    newPasswordPh: 'New Password',
    backToSignIn: 'Back to Sign In',
    changeEmail: 'Change email',
    newPasswordLabel: 'New Password',
    passwordUpdated: 'Password Updated',
    verificationCode: 'Verification Code',
    updatePassword: 'Update Password',
    verifyCode: 'Verify Code',
    sayHello: 'Say hello 👋',
    send: 'Send',
    getStarted: 'Get Started',
    offline: 'No internet connection',
    unread: 'unread',
    noNotificationsYet: 'No notifications yet',
    accepted: 'Accepted',
    rejected: 'Rejected',
    // Onboarding form
    whatsYourName: "What's your name?",
    enterYourName: 'Enter your name',
    yourGender: 'Your gender',
    genderOther: 'Other',
    dateOfBirth: 'Date of Birth',
    hourLabel: 'HOUR',
    minLabel: 'MIN',
    addBirthTime: 'Add birth time',
    placeOfBirth: 'Place of Birth',
    country: 'Country',
    selectCountry: 'Select Country',
    cityLabel: 'City',
    summary: 'Summary',
    searchCountry: 'Search country...',
    noCitiesFound: 'No cities found',
    saveAndStart: 'Save & Start',
    nickname: 'Nickname',
    birthDate: 'Birth Date',
    birthTime: 'Birth Time',
    birthPlace: 'Birth Place',
    language: 'Language',
    theme: 'Theme',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    notifications: 'Notifications',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    about: 'About',
    version: 'Version',

    // Zodiac Signs
    aries: 'Aries',
    taurus: 'Taurus',
    gemini: 'Gemini',
    cancer: 'Cancer',
    leo: 'Leo',
    virgo: 'Virgo',
    libra: 'Libra',
    scorpio: 'Scorpio',
    sagittarius: 'Sagittarius',
    capricorn: 'Capricorn',
    aquarius: 'Aquarius',
    pisces: 'Pisces',

    // Months
    january: 'January',
    february: 'February',
    march: 'March',
    april: 'April',
    may: 'May',
    june: 'June',
    july: 'July',
    august: 'August',
    september: 'September',
    october: 'October',
    november: 'November',
    december: 'December',

    // Daily Oracle Messages
    dailyOracle1: 'The universe is speaking to you today, listen.',
    dailyOracle2: 'The stars illuminate your path.',
    dailyOracle3: 'The power within you is about to awaken.',
    dailyOracle4: 'Be open to surprises today.',
    dailyOracle5: 'Listen to your heart.',
    dailyOracle6: 'New opportunities are knocking.',
    dailyOracle7: 'Patience is the greatest virtue.',
    dailyOracle8: 'Love opens every door.',
    dailyOracle9: 'Are you ready for change?',
    dailyOracle10: 'Today is a turning point.',
    dailyOracle11: 'Make your dreams come true.',
    dailyOracle12: 'Old closes, new opens.',
    dailyOracle13: 'Trust your intuition.',
    dailyOracle14: 'The universe continues to work its plan.',
    dailyOracle15: 'Be grateful, abundance will come.',
    dailyOracle16: 'Keep your mind clear.',
    dailyOracle17: 'Love is everywhere.',
    dailyOracle18: 'Your courage will be rewarded.',
    dailyOracle19: 'Take a deep breath.',
    dailyOracle20: 'Walk in the light.',
    dailyOracle21: 'Release your creativity.',
    dailyOracle22: 'Leave the past, embrace the present.',
    dailyOracle23: 'Every end is a new beginning.',
    dailyOracle24: 'Create your own magic.',
    dailyOracle25: 'The stars are on your side.',
    dailyOracle26: 'Faith moves mountains.',
    dailyOracle27: 'Find inner peace.',
    dailyOracle28: 'Laugh a lot today.',
    dailyOracle29: 'Listen to the voice of nature.',
    dailyOracle30: 'Dreams can come true.',
    dailyOracle31: 'You are special and unique.',

    // Navigation
    home: 'Home',
    forum: 'Forum',
    chat: 'Chat',
    messages: 'Messages',

    // AI Chat
    askQuestion: 'Ask a question...',
    sendMessage: 'Send message',
    aiThinking: 'AI is thinking...',

    // Errors
    errorGeneral: 'An error occurred',
    errorNetwork: 'Connection error',
    errorAuth: 'Authentication error',
    tryAgain: 'Try Again',
};
