// Turkish translations
export const tr = {
    // General
    appName: 'Kosmos Astro',
    appTitle: 'KOSMOS ASTRO',
    appDescription: 'Yıldızlara giden yolculuk',
    hello: 'Merhaba',
    guest: 'Misafir',
    loading: 'Yukleniyor...',
    error: 'Hata',
    success: 'Basarili',
    cancel: 'Iptal',
    save: 'Kaydet',
    delete: 'Sil',
    edit: 'Duzenle',
    close: 'Kapat',
    back: 'Geri',
    next: 'Ileri',
    done: 'Tamam',
    search: 'Ara',
    settings: 'Ayarlar',
    profile: 'Profil',
    logout: 'Cikis Yap',
    login: 'Giris Yap',
    register: 'Kayit Ol',
    skip: 'Geç',
    discover: 'Keşfet',
    continueButton: 'Devam Et',

    // Onboarding
    onboardingTitle1: 'Yıldızlara Bak',
    onboardingSubtitle1: 'EVRENLE BAĞLAN',
    onboardingDesc1: 'Astroloji dünyasını keşfet ve kozmik enerjilerle bağlan.',
    onboardingTitle2: 'Geleceğini Keşfet',
    onboardingSubtitle2: 'TAROT VE ASTROLOJİ',
    onboardingDesc2: 'Tarot kartları ve astroloji ile kaderinin sırlarını çöz.',
    onboardingTitle3: 'Yolculuğa Başla',
    onboardingSubtitle3: 'REHBERLERLE TANIŞIN',
    onboardingDesc3: 'Uzman astrologlarımız sana yol göstersin.',

    // Auth
    email: 'E-posta',
    password: 'Sifre',
    confirmPassword: 'Sifre Tekrar',
    forgotPassword: 'Sifremi Unuttum',
    orContinueWith: 'veya devam et',
    continueWithGoogle: 'Google ile Devam Et',
    continueWithApple: 'Apple ile Devam Et',
    alreadyHaveAccount: 'Zaten hesabiniz var mi?',
    dontHaveAccount: 'Hesabiniz yok mu?',
    signIn: 'Giriş Yap',
    signUp: 'Kayıt Ol',
    tagline: 'Yıldızlara giden yolculuk',
    emailOrUsername: 'E-posta veya Kullanıcı Adı',
    emailAddress: 'E-posta Adresi',
    username: 'Kullanıcı Adı',
    usernameTaken: 'Bu kullanıcı adı zaten alınmış',
    continueAsGuest: 'Misafir Olarak Devam Et',
    orText: 'veya',
    termsNotice: 'Devam ederek Hizmet Şartları’nı kabul etmiş olursun',
    fillAllFields: 'Lütfen tüm alanları doldurun',
    invalidEmail: 'Geçerli bir e-posta adresi girin',
    enterUsername: 'Lütfen bir kullanıcı adı girin',
    usernameTooShort: 'Kullanıcı adı en az 3 karakter olmalı',
    passwordsNoMatch: 'Şifreler eşleşmiyor',
    passwordTooShort: 'Şifre en az 6 karakter olmalı',
    tooManyAttempts: 'Çok fazla deneme. Lütfen birkaç dakika sonra tekrar deneyin.',
    connectionError: 'Sunucuya bağlanılamadı. İnternet bağlantınızı kontrol edin.',
    authFailed: 'Bir hata oluştu. Lütfen tekrar deneyin.',
    verifyEmail: 'E-postanı Doğrula',
    verifyEmailSubtitle: '6 haneli kodu şu adrese gönderdik:',
    verifyCreateAccount: 'Doğrula ve Hesap Oluştur',
    enterSixDigitCode: 'Lütfen 6 haneli kodu girin',
    resendCode: 'Kodu Tekrar Gönder',
    resendCodeIn: 'Tekrar gönder:',
    emailAlreadyRegistered: 'Bu e-posta zaten kayıtlı. Giriş yapmayı deneyin.',
    failedSendCode: 'Doğrulama kodu gönderilemedi.',
    registrationFailed: 'Kayıt başarısız. Lütfen tekrar deneyin.',
    chooseLanguage: 'Dilini Seç',
    chooseLanguageSub: 'Bunu daha sonra ayarlardan değiştirebilirsin',
    changeLanguage: 'Dili Değiştir',
    changeLanguageSub: 'Tercih ettiğin dili seç',

    // Home
    advisors: 'Danismanlar',
    dailyMessage: 'Gunun Mesaji',
    seekingAnswer: 'Cevap Ariyorsun...',
    exploreAndCalculate: 'Kesfet & Hesapla',
    premiumFeatures: 'Premium Ozellikler',
    pro: 'PRO',
    newFeature: 'Yeni',

    // Features
    birthChart: 'Dogum Haritasi',
    readYourFate: 'Kaderini Oku',
    tarotReading: 'Tarot Fali',
    selectCards: 'Kartlarini Sec',
    palmReading: 'El Fali',
    readLines: 'Cizgilerini Oku',
    coffeeReading: 'Kahve Fali',
    traditionalFortune: 'Geleneksel Fal',
    dreamInterpretation: 'Ruya Tabiri',
    subconscious: 'Bilincaltini Kesfet',
    nameAnalysis: 'Isim Analizi',
    numerology: 'Numeroloji',
    synastryCompatibility: 'Uyum Analizi',
    loveAnalysis: 'Ask Uyumu',
    faceReading: 'Yuz Okuma',
    physiognomy: 'Fizyognomi',
    vedicChart: 'Vedik Harita',
    indianAstrology: 'Hint Astrolojisi',
    angelCards: 'Melek Kartlari',
    messageFromAngels: 'Meleklerin Mesaji',
    risingSign: 'Yukselen Burc',
    discoverYourMask: 'Maskeni Kesfet',
    planetHours: 'Gezegen Saatleri',
    cosmicTiming: 'Kozmik Zamanlama',
    findSoulmate: 'Ruh Esini Bul',
    cosmicMatching: 'Kozmik Eslestirme',
    drawSoulmate: 'Ruh Eşini Çiz',
    karmicPortrait: 'Karmik Portre',

    // Moon Phases
    moonPhases: 'Ay Evreleri',
    moonPhaseNew: 'Yeni Ay',
    moonPhaseNewDesc: 'Yeni baslangiclarin zamani',
    moonPhaseWaxingCrescent: 'Hilal',
    moonPhaseWaxingCrescentDesc: 'Niyetleri belirle',
    moonPhaseFirstQuarter: 'Ilk Dordun',
    moonPhaseFirstQuarterDesc: 'Harekete gec',
    moonPhaseWaxingGibbous: 'Sisikin Ay',
    moonPhaseWaxingGibbousDesc: 'Gelistir ve iyilestir',
    moonPhaseFull: 'Dolunay',
    moonPhaseFullDesc: 'Zirvede enerji',
    moonPhaseWaningGibbous: 'Kuculen Sisikin',
    moonPhaseWaningGibbousDesc: 'Minnettar ol',
    moonPhaseLastQuarter: 'Son Dordun',
    moonPhaseLastQuarterDesc: 'Birak gitsin',
    moonPhaseWaningCrescent: 'Kuculen Hilal',
    moonPhaseWaningCrescentDesc: 'Dinlen ve yenilen',

    // Streak
    dailyStreak: 'Gunluk Seri',
    claimReward: 'Odulu Al',
    streakDays: 'gun seri',
    comeBackTomorrow: 'Yarin tekrar gel!',
    rewardClaimed: 'Odul alindi!',

    // Premium
    premium: 'Premium',
    goPremium: 'Premium\'a Gec',
    unlockAllFeatures: 'Tum ozelliklerin kilidini ac',
    monthlyPlan: 'Aylik Plan',
    yearlyPlan: 'Yillik Plan',
    bestValue: 'En Iyi Deger',
    freeTrial: 'Ucretsiz Deneme',

    // Tokens
    tokens: 'Altin',
    buyTokens: 'Altin Satin Al',
    watchAdForTokens: 'Reklam Izle, Altin Kazan',
    insufficientTokens: 'Yetersiz altin',

    // Profile
    editProfile: 'Profili Duzenle',
    dayStreak: 'Günlük Seri',
    friends: 'Arkadaşlar',
    earned: 'Kazanılan',
    shareInviteCode: 'Davet Kodunu Paylaş',
    inviteFriends: 'Arkadaşlarını Davet Et',
    // Draw Soulmate
    revealSoulmate: 'Ruh Eşini Ortaya Çıkar',
    soulmateSubtitle: 'Doğum bilgilerini gir; yıldızlar senin için yaratılan kişinin portresini çizsin.',
    usingProfileData: 'Kayıtlı profil bilgilerin kullanılıyor',
    profileDataAvailable: 'Profil bilgilerin hazır',
    useMyData: 'Bilgilerimi Kullan',
    birthCity: 'Doğum Şehri',
    lookingFor: 'Kimi Arıyorsun',
    genderFemale: 'Kadın',
    genderMale: 'Erkek',
    genderAny: 'Farketmez',
    moonTokens: 'Ay Taşı',
    balance: 'Bakiye',
    generatePortrait: 'Portre Oluştur',
    yourSoulmate: 'Ruh Eşin',
    cosmicPortraitSubtitle: 'Yıldızlara yazılmış kozmik bir portre',
    cosmicPortrait: 'KOZMİK PORTRE',
    physicalTraits: 'Fiziksel Özellikler',
    personalityLabel: 'Kişilik',
    whereYouMeet: 'Nerede Tanışabilirsiniz',
    cosmicCompatibility: 'Kozmik Uyum',
    sketching: 'Çiziliyor…',
    soulmateProgress1: 'Yıldızlar okunuyor...',
    soulmateProgress2: 'Göksel hizalanmalar haritalanıyor...',
    soulmateProgress3: 'Hatlar çiziliyor...',
    soulmateProgress4: 'Kozmik detaylar ekleniyor...',
    soulmateProgress5: 'Portre tamamlanıyor...',
    // Dream Interpreter
    dreamInterpreter: 'Rüya Yorumcusu',
    popularDreams: 'Popüler rüyalar',
    interpreting: 'yorumlanıyor...',
    pastDreams: 'Geçmiş Rüyalar',
    noPastDreams: 'Henüz kayıtlı rüya yok.',
    tellYourDream: 'Rüyanı anlat...',
    dreamSuggestion1: 'Rüyamda uçuyordum — ne anlama geliyor?',
    dreamSuggestion2: 'Dişlerim dökülüyordu.',
    dreamSuggestion3: 'Kovalanıyordum ama koşamıyordum.',
    dreamSuggestion4: 'Vefat etmiş birini gördüm.',
    dreamSuggestion5: 'Sınava geç kaldım ve sınıfı bulamadım.',
    dreamSuggestion6: 'Çok yüksek bir yerden düşüyordum.',
    // Tarot
    revealReading: 'Yorumunu Aç',
    tapCardsPre: 'Aşağıdan',
    tapCardsPost: 'kart daha seç',
    notEnoughTokensPremium: 'Yeterli jeton yok. Daha fazlası için Premium’a göz at.',
    yourSpread: 'Açılımın',
    upright: 'Düz',
    reversed: 'Ters',
    combinedReading: 'Birleşik Yorum',
    howCardsConnect: 'Kartların birbiriyle nasıl bağlandığı',
    drawNewCards: 'Yeni Kart Çek',
    posPast: 'Geçmiş',
    posPresent: 'Şimdi',
    posFuture: 'Gelecek',
    posPastDesc: 'Geçip gidenler',
    posPresentDesc: 'Mevcut enerji',
    posFutureDesc: 'Gelecek olanlar',
    // Birth Chart
    birthChartUpper: 'DOĞUM HARİTASI',
    birthDateUpper: 'DOĞUM TARİHİ',
    birthTimeUpper: 'DOĞUM SAATİ',
    birthCityUpper: 'DOĞUM ŞEHRİ',
    analysisResult: 'ANALİZ SONUCU',
    planetPositions: 'GEZEGEN KONUMLARI',
    elementBalance: 'ELEMENT DENGESİ',
    qualityBalance: 'NİTELİK DENGESİ',
    yourSunSign: 'GÜNEŞ BURCUN',
    yourMoonSign: 'AY BURCUN',
    yourRisingSign: 'YÜKSELEN BURCUN',
    calculate: 'Hesapla',
    newCalculation: 'Yeni Hesaplama',
    confirm: 'Onayla',
    selectDate: 'TARİH SEÇ',
    selectTime: 'SAAT SEÇ',
    searchCity: 'Şehir ara...',
    // Profile extras
    signOut: 'Çıkış Yap',
    premiumActive: 'Premium Aktif',
    unlockPremium: 'Premium’u Aç',
    allFeaturesUnlocked: 'Tüm özellikler açık',
    premiumPerks: 'Sınırsız yorum · AI içgörüler · Reklamsız',
    upgrade: 'Yükselt',
    becomeAstrologer: 'Astrolog Ol',
    becomeAstrologerSub: 'Bilgini paylaş ve kazan',
    referralReward: 'Davet ettiğin her arkadaş için 150 jeton kazan!',
    // Zodiac signs
    signAries: 'Koç', signTaurus: 'Boğa', signGemini: 'İkizler', signCancer: 'Yengeç',
    signLeo: 'Aslan', signVirgo: 'Başak', signLibra: 'Terazi', signScorpio: 'Akrep',
    signSagittarius: 'Yay', signCapricorn: 'Oğlak', signAquarius: 'Kova', signPisces: 'Balık',
    elFire: 'Ateş', elEarth: 'Toprak', elAir: 'Hava', elWater: 'Su',
    // Numerology
    fullName: 'Ad Soyad',
    yourFullName: 'Ad ve soyadın',
    useSavedBirthDate: 'Kayıtlı doğum tarihini kullan',
    nameNumber: 'İsim Sayısı',
    lifePathNumber: 'Yaşam Yolu Sayısı',
    cosmicConnection: 'Kozmik Bağlantı',
    newAnalysis: 'Yeni Analiz',
    dayLabel: 'Gün',
    monthLabel: 'Ay',
    yearLabel: 'Yıl',
    // Friends buttons
    addFriendBtn: 'Ekle',
    acceptBtn: 'Kabul Et',
    rejectBtn: 'Reddet',
    friendLabel: 'Arkadaş',
    cancelRequest: 'Geri Çek',
    wantsToBeFriends: 'seninle arkadaş olmak istiyor',
    signOutConfirm: 'Çıkış yapmak istediğine emin misin?',
    comingSoon: 'Yakında',
    comingSoonMsg: 'Bu özellik yakında bir güncellemeyle gelecek.',
    pastConversations: 'Geçmiş Sohbetler',
    noPastConversations: 'Henüz geçmiş sohbet yok.',
    askAstroAI: 'Astro AI’ya sor...',
    thinkingShort: 'düşünüyor...',
    love: 'Aşk',
    career: 'Kariyer',
    health: 'Sağlık',
    energy: 'Enerji',
    luckyColor: 'Şanslı Renk',
    luckyNumber: 'Şanslı Sayılar',
    element: 'Element',
    dailyHoroscopeSuffix: 'Günlük Burç Yorumun',
    // Shared feature labels
    camera: 'Kamera',
    gallery: 'Galeri',
    newReading: 'Yeni Fal',
    retake: 'Tekrar Çek',
    pleaseWait: 'Lütfen bekleyin...',
    // Synastry
    challenge: 'Zorluk',
    dimensions: 'Boyutlar',
    overall: 'GENEL',
    selectSign: 'Burç Seç',
    // Face Reading
    aiFaceAnalysis: 'AI Yüz Analizi',
    characterSummary: 'Karakter Özeti',
    dominantElement: 'Baskın Element',
    facialRegionAnalysis: 'Yüz Bölgesi Analizi',
    howItWorks: 'Nasıl çalışır',
    // Palm Reading
    alignPalmGuide: 'Avucunu kılavuzla hizala',
    chooseAnalysis: 'Analiz Seç',
    deepInsights: 'Derin İçgörüler',
    fingerShapeAnalysis: 'Parmak Şekli Analizi',
    moneyTriangle: 'Para Üçgeni',
    mountAnalysis: 'Tepe Analizi',
    overallSummary: 'Genel Özet',
    palmLines: 'El Çizgileri',
    palmistryAnalysis: 'El Falı Analizi',
    relationshipLines: 'İlişki Çizgileri',
    tipsGreatReading: 'İyi Bir Fal İçin İpuçları',
    travelLines: 'Seyahat Çizgileri',
    palmReadingReady: 'El Falın Hazır',
    // Coffee Fortune
    interpretingSymbols: 'Semboller yorumlanıyor',
    readingGrounds: 'Telve okunuyor...',
    yourReading: 'Falın',
    // Rising Sign
    birthYear: 'Doğum Yılı',
    discoverRisingSign: 'Yükselen Burcunu Keşfet',
    faceYouShow: 'Dünyaya gösterdiğin yüzü keşfet',
    selectBirthPlace: 'Doğum Yeri Seç',
    selectBirthTime: 'Doğum Saati Seç',
    selectBirthYear: 'Doğum Yılı Seç',
    block: 'Engelle',
    unblock: 'Engeli Kaldır',
    blocked: 'Engellenenler',
    requests: 'İstekler',
    // Vedic Chart
    ancientWisdom: 'Doğu’nun Kadim Bilgeliği',
    ayurvedicConstitution: 'Ayurvedik Yapı',
    deity: 'Tanrı/Tanrıça',
    kundliChart: 'Kundli Haritası',
    meaning: 'Anlam',
    northIndian: 'Kuzey Hint',
    southIndian: 'Güney Hint',
    ruler: 'Yönetici',
    rulingPlanet: 'Yönetici Gezegen',
    lightOfSoul: 'Ruhun Işığı',
    mirrorOfMind: 'Zihnin Aynası',
    mythologicalDeity: 'Mitolojik Tanrı',
    outerPlanets: 'Dış Gezegenler',
    // Find Soulmate / History / Astrologers
    yourSign: 'Senin Burcun',
    answer: 'Cevap',
    consultants: 'Danışmanlar',
    cosmicMessage: 'Kozmik Mesaj',
    favorites: 'Favoriler',
    historyTitle: 'Geçmiş',
    question: 'Soru',
    cosmicGuides: 'Kozmik Rehberler',
    mostPopular: 'En Popüler',
    // Astrologer chat / profile / panel
    additionalDetails: 'Ek Detaylar',
    reportAstrologer: 'Astroloğu Şikayet Et',
    submitReport: 'Şikayeti Gönder',
    reportReason: 'Bu şikayetin sebebi nedir?',
    addCaption: 'Açıklama ekle...',
    messagePh: 'Mesaj...',
    describeHappened: 'İsteğe bağlı: ne olduğunu anlat...',
    response: 'Yanıt',
    sessions: 'Seans',
    specializations: 'Uzmanlıklar',
    clientMessages: 'Müşteri Mesajları',
    earnings: 'Kazanç',
    client: 'Müşteri',
    writeReply: 'Yanıtını yaz...',
    aboutYou: 'Hakkında',
    applicationStatus: 'Başvuru Durumu',
    personalInfo: 'Kişisel Bilgiler',
    prevNotApproved: 'Önceki başvuru onaylanmadı',
    selectExpertise: 'En az bir uzmanlık alanı seç',
    specialties: 'Uzmanlıklar',
    underReview: 'İnceleniyor',
    canSubmitNew: 'Aşağıdan yeni bir başvuru gönderebilirsin.',
    experiencePh: 'Deneyimini ve yaklaşımını anlat...',
    yearsExperiencePh: 'Deneyim yılı',
    annualPlan: 'Yıllık Plan',
    billedYearly: 'Yılda bir kez faturalanır',
    cancelAnytime: 'İstediğin zaman iptal et',
    kosmosPremium: 'Kosmos Premium',
    moonTokensUpper: 'AY TAŞI',
    privacyShort: 'Gizlilik',
    restore: 'Geri Yükle',
    subscription: 'ABONELİK',
    termsShort: 'Şartlar',
    tokenCostRef: 'Jeton Maliyet Tablosu',
    whatYouGet: 'NELER KAZANIRSIN',
    promoCodePh: 'Promosyon kodu',
    changePassword: 'Şifre Değiştir',
    currentPassword: 'Mevcut Şifre',
    emailCode: 'E-posta Kodu',
    emailVerified: 'E-posta doğrulandı',
    enterCurrentPassword: 'Mevcut şifreni gir',
    passwordChanged: 'Şifre Değiştirildi',
    sendCode: 'Kod Gönder',
    setNewPassword: 'Yeni şifreni belirle',
    verify: 'Doğrula',
    confirmNewPasswordPh: 'Yeni Şifre Tekrar',
    currentPasswordPh: 'Mevcut Şifre',
    newPasswordPh: 'Yeni Şifre',
    backToSignIn: 'Girişe Dön',
    changeEmail: 'E-postayı değiştir',
    newPasswordLabel: 'Yeni Şifre',
    passwordUpdated: 'Şifre Güncellendi',
    verificationCode: 'Doğrulama Kodu',
    updatePassword: 'Şifreyi Güncelle',
    verifyCode: 'Kodu Doğrula',
    sayHello: 'Merhaba de 👋',
    send: 'Gönder',
    getStarted: 'Başla',
    offline: 'İnternet bağlantısı yok',
    unread: 'okunmamış',
    noNotificationsYet: 'Henüz bildirim yok',
    accepted: 'Kabul edildi',
    rejected: 'Reddedildi',
    // Onboarding form
    whatsYourName: 'Adın ne?',
    enterYourName: 'Adını gir',
    yourGender: 'Cinsiyetin',
    genderOther: 'Diğer',
    dateOfBirth: 'Doğum Tarihi',
    hourLabel: 'SAAT',
    minLabel: 'DAK',
    addBirthTime: 'Doğum saati ekle',
    placeOfBirth: 'Doğum Yeri',
    country: 'Ülke',
    selectCountry: 'Ülke Seç',
    cityLabel: 'Şehir',
    summary: 'Özet',
    searchCountry: 'Ülke ara...',
    noCitiesFound: 'Şehir bulunamadı',
    saveAndStart: 'Kaydet ve Başla',
    nickname: 'Kullanici Adi',
    birthDate: 'Dogum Tarihi',
    birthTime: 'Dogum Saati',
    birthPlace: 'Dogum Yeri',
    language: 'Dil',
    theme: 'Tema',
    darkMode: 'Karanlik Mod',
    lightMode: 'Aydinlik Mod',
    notifications: 'Bildirimler',
    privacyPolicy: 'Gizlilik Politikasi',
    termsOfService: 'Kullanim Sartlari',
    about: 'Hakkinda',
    version: 'Versiyon',

    // Zodiac Signs
    aries: 'Koc',
    taurus: 'Boga',
    gemini: 'Ikizler',
    cancer: 'Yengec',
    leo: 'Aslan',
    virgo: 'Basak',
    libra: 'Terazi',
    scorpio: 'Akrep',
    sagittarius: 'Yay',
    capricorn: 'Oglak',
    aquarius: 'Kova',
    pisces: 'Balik',

    // Months
    january: 'Ocak',
    february: 'Subat',
    march: 'Mart',
    april: 'Nisan',
    may: 'Mayis',
    june: 'Haziran',
    july: 'Temmuz',
    august: 'Agustos',
    september: 'Eylul',
    october: 'Ekim',
    november: 'Kasim',
    december: 'Aralik',

    // Daily Oracle Messages
    dailyOracle1: 'Bugun evren seninle konusuyor, kulak ver.',
    dailyOracle2: 'Yildizlar yolunu aydinlatiyor.',
    dailyOracle3: 'Icindeki guc uyanmak uzere.',
    dailyOracle4: 'Bugun surprizlere acik ol.',
    dailyOracle5: 'Kalbinin sesini dinle.',
    dailyOracle6: 'Yeni firsatlar kapiyi caliyor.',
    dailyOracle7: 'Sabir en buyuk erdemdir.',
    dailyOracle8: 'Sevgi her kaptiyi acar.',
    dailyOracle9: 'Degisim icin hazir misin?',
    dailyOracle10: 'Bugun bir donum noktasi.',
    dailyOracle11: 'Ruya gordugunu gerceklestir.',
    dailyOracle12: 'Eski kapanir, yeni acilir.',
    dailyOracle13: 'Sezgilerine guven.',
    dailyOracle14: 'Evren planini islemeye devam ediyor.',
    dailyOracle15: 'Minnettar ol, bereket gelsin.',
    dailyOracle16: 'Zihnini temiz tut.',
    dailyOracle17: 'Ask her yerde.',
    dailyOracle18: 'Cesaretin odullendirilecek.',
    dailyOracle19: 'Derin bir nefes al.',
    dailyOracle20: 'Isik icinde yuru.',
    dailyOracle21: 'Yaraticiligini serbest birak.',
    dailyOracle22: 'Gecmisi birak, simdiyi kucakla.',
    dailyOracle23: 'Her son yeni bir baslangictir.',
    dailyOracle24: 'Kendi buyunu kendin yarat.',
    dailyOracle25: 'Yildizlar senden yana.',
    dailyOracle26: 'Inanc daglari yerinden oynatir.',
    dailyOracle27: 'Icsel huzuru bul.',
    dailyOracle28: 'Bol bol gul bugun.',
    dailyOracle29: 'Doganin sesini dinle.',
    dailyOracle30: 'Hayaller gercek olabilir.',
    dailyOracle31: 'Sen ozel ve essizsin.',

    // Navigation
    home: 'Ana Sayfa',
    forum: 'Forum',
    chat: 'Sohbet',
    messages: 'Mesajlar',

    // AI Chat
    askQuestion: 'Soru sor...',
    sendMessage: 'Mesaj gonder',
    aiThinking: 'AI dusunuyor...',

    // Errors
    errorGeneral: 'Bir hata olustu',
    errorNetwork: 'Baglanti hatasi',
    errorAuth: 'Kimlik dogrulama hatasi',
    tryAgain: 'Tekrar Dene',
};
